### ISSUE TITLE
Kemono post search  Feature

### ISSUE THREAD

**Issue by MD1782006** [kitsumed/mihonyomi-extensions#20]
### Source name

kemono

### Describe your suggested feature

The provided Extension can only search in the Artists section and some time have to find the post from post title for that reason kemono has a different Posts section so can you add that in Extension

sorry for the bad english
   

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the tachiyomi compatible app.
- [X] I have the latest extension version.
- [X] I will fill out all of the requested information in this form.

**Comment by kitsumed** [comment]
Hi there, I am not sure to understand. Is this a feature request for the current Komga extension or a extension request for a application named kemono?

If this is a extension request for kemono, I can't find any open-source project named like that, and the first result that came when searching for it was a "public archiver" website.

Please note that I won't do extensions if they aren't self-hosted by the user and require scrapping instead of the use of a API. I might always refuse even if these criteria are met as I currently use Komga and don't want to put my time on something that I might not use myself.
